/**
 * Medical Tests Catalog Data
 * Certified Medical Laboratory & Diagnostic Services
 */
const MEDICAL_TESTS = [
  {
    id: "malaria-microscopy",
    name: "Malaria Parasite Microscopy (Blood Smear)",
    category: "infectious",
    categoryLabel: "Infectious Diseases",
    price: 15000,
    sampleType: "Capillary / Whole Blood",
    turnaround: "30 - 45 Mins",
    fasting: "No fasting required",
    badge: "Rapid Result",
    icon: "microscope",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=600&q=80",
    description: "Gold-standard thick and thin film microscopic examination to detect and quantify Plasmodium species causing malaria.",
    parameters: ["Plasmodium detection (P. falciparum, P. vivax)", "Parasite density count (per μL)", "Smear morphology review"]
  },
  {
    id: "malaria-rdt",
    name: "Malaria Rapid Diagnostic Test (RDT Antigen)",
    category: "infectious",
    categoryLabel: "Infectious Diseases",
    price: 12000,
    sampleType: "Fingerstick Blood",
    turnaround: "15 - 20 Mins",
    fasting: "No fasting required",
    badge: "Express",
    icon: "zap",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80",
    description: "Rapid immunochromatographic antigen detection for quick confirmation of active malaria infection in minutes.",
    parameters: ["Pf-HRP2 antigen", "Pan-Plasmodium pLDH enzyme"]
  },
  {
    id: "fasting-blood-sugar",
    name: "Fasting Blood Sugar (FBS / Glucose)",
    category: "metabolic",
    categoryLabel: "Metabolic & Diabetes",
    price: 10000,
    sampleType: "Fluoride Plasma / Serum",
    turnaround: "30 Mins",
    fasting: "Strict 8 - 10 hours fasting",
    badge: "Essential",
    icon: "droplet",
    image: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=600&q=80",
    description: "Screening and diagnostic evaluation of baseline blood glucose levels to diagnose pre-diabetes and diabetes mellitus.",
    parameters: ["Fasting Plasma Glucose (mg/dL or mmol/L)", "Glycemic status classification"]
  },
  {
    id: "random-blood-sugar",
    name: "Random Blood Sugar (RBS)",
    category: "metabolic",
    categoryLabel: "Metabolic & Diabetes",
    price: 8000,
    sampleType: "Capillary / Venous Blood",
    turnaround: "15 Mins",
    fasting: "No fasting required",
    badge: "Quick Check",
    icon: "activity",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80",
    description: "Immediate check of current circulating blood glucose levels at any time of day to assess acute hypoglycemia or hyperglycemia.",
    parameters: ["Circulating Blood Glucose level"]
  },
  {
    id: "hba1c-glycated",
    name: "HbA1c (Glycated Hemoglobin - 3 Month Average)",
    category: "metabolic",
    categoryLabel: "Metabolic & Diabetes",
    price: 28000,
    sampleType: "EDTA Whole Blood",
    turnaround: "2 - 3 Hours",
    fasting: "No fasting required",
    badge: "Recommended",
    icon: "clock",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
    description: "Accurate reflection of average blood sugar control over the past 90 days. Does not fluctuate with recent meals.",
    parameters: ["Glycated Hemoglobin %", "Estimated Average Glucose (eAG)", "Diabetic control score"]
  },
  {
    id: "lipid-profile-cholesterol",
    name: "Complete Lipid Profile (Cholesterol Panel)",
    category: "cardiac",
    categoryLabel: "Heart & Vascular",
    price: 32000,
    sampleType: "Serum",
    turnaround: "2 - 4 Hours",
    fasting: "9 - 12 hours overnight fasting",
    badge: "Popular",
    icon: "heart-pulse",
    image: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=600&q=80",
    description: "Comprehensive assessment of cardiovascular risk by measuring bad and good cholesterol along with circulating triglycerides.",
    parameters: ["Total Cholesterol", "HDL (Good Cholesterol)", "LDL (Bad Cholesterol)", "Triglycerides", "VLDL", "Cholesterol/HDL Ratio"]
  },
  {
    id: "complete-blood-count",
    name: "Complete Blood Count (CBC / Full Blood Count)",
    category: "routine",
    categoryLabel: "Routine Health",
    price: 22000,
    sampleType: "EDTA Whole Blood",
    turnaround: "1 Hour",
    fasting: "No fasting required",
    badge: "Comprehensive",
    icon: "file-text",
    image: "https://images.unsplash.com/photo-1584362917165-526a968579e8?auto=format&fit=crop&w=600&q=80",
    description: "Broad screening test that checks white cells, red cells, platelets, and hemoglobin to detect anemia, infections, and clotting disorders.",
    parameters: ["Hemoglobin (Hb)", "RBC count", "WBC total & 5-part differential", "Platelet count", "Hematocrit (PCV)", "MCV, MCH, MCHC"]
  },
  {
    id: "widal-typhoid-test",
    name: "Widal Agglutination Test (Typhoid Serology)",
    category: "infectious",
    categoryLabel: "Infectious Diseases",
    price: 14000,
    sampleType: "Serum",
    turnaround: "45 Mins",
    fasting: "No fasting required",
    badge: "Common",
    icon: "shield-alert",
    image: "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&w=600&q=80",
    description: "Serological test detecting Salmonella enterica antibodies (O and H antigens) to assist in enteric typhoid fever diagnosis.",
    parameters: ["S. Typhi O & H Titers", "S. Paratyphi A & B Titers"]
  },
  {
    id: "liver-function-test",
    name: "Liver Function Test Panel (LFT)",
    category: "routine",
    categoryLabel: "Routine Health",
    price: 35000,
    sampleType: "Serum",
    turnaround: "3 - 4 Hours",
    fasting: "8 - 10 hours preferred",
    badge: "Full Panel",
    icon: "clipboard-check",
    image: "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=600&q=80",
    description: "Evaluates liver health, inflammation, bile duct clearance, and protein synthesis capacity of the hepatic system.",
    parameters: ["Total & Direct Bilirubin", "SGPT / ALT", "SGOT / AST", "Alkaline Phosphatase (ALP)", "Total Protein", "Albumin & Globulin ratio"]
  },
  {
    id: "kidney-function-test",
    name: "Kidney / Renal Function Test (RFT / KFT)",
    category: "routine",
    categoryLabel: "Routine Health",
    price: 30000,
    sampleType: "Serum",
    turnaround: "2 - 3 Hours",
    fasting: "Hydration recommended",
    badge: "Vital Check",
    icon: "activity",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80",
    description: "Measures kidney filtration efficiency, urea clearance, and serum electrolyte balances to monitor renal wellness.",
    parameters: ["Serum Creatinine", "Blood Urea Nitrogen (BUN)", "Estimated GFR (eGFR)", "Sodium (Na+)", "Potassium (K+)", "Chloride (Cl-)"]
  },
  {
    id: "urinalysis-routine",
    name: "Complete Urinalysis (Physical, Chemical & Microscopy)",
    category: "routine",
    categoryLabel: "Routine Health",
    price: 12000,
    sampleType: "Midstream Clean-Catch Urine",
    turnaround: "30 Mins",
    fasting: "First morning void preferred",
    badge: "Quick 30m",
    icon: "filter",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Detailed microscopic and dipstick chemical analysis detecting urinary tract infections (UTI), kidney stress, and proteinuria.",
    parameters: ["Leukocytes & Nitrites", "Protein & Glucose", "Urobilinogen & Ketones", "Microscopic pus cells, RBCs, epithelial cells, crystals"]
  },
  {
    id: "thyroid-profile-tsh",
    name: "Thyroid Profile (TSH, Free T3, Free T4)",
    category: "specialized",
    categoryLabel: "Hormones & Specialized",
    price: 45000,
    sampleType: "Serum",
    turnaround: "Same Day (4 - 6 Hours)",
    fasting: "Morning sample recommended",
    badge: "Hormone Panel",
    icon: "dna",
    image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=600&q=80",
    description: "Pinpoints underactive (hypothyroidism) or overactive (hyperthyroidism) thyroid gland regulation and metabolic imbalance.",
    parameters: ["Thyroid Stimulating Hormone (TSH)", "Free Triiodothyronine (FT3)", "Free Thyroxine (FT4)"]
  },
  {
    id: "hepatitis-b-screening",
    name: "Hepatitis B Surface Antigen (HBsAg Screening)",
    category: "infectious",
    categoryLabel: "Infectious Diseases",
    price: 16000,
    sampleType: "Serum / Whole Blood",
    turnaround: "30 - 45 Mins",
    fasting: "No fasting required",
    badge: "Screening",
    icon: "shield-check",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80",
    description: "High-sensitivity screening for Hepatitis B virus antigen to detect current viral infection and transmission risk.",
    parameters: ["HBsAg qualitatively reported (Reactive / Non-Reactive)"]
  },
  {
    id: "vitamin-d-total",
    name: "Vitamin D (25-Hydroxy D2/D3)",
    category: "specialized",
    categoryLabel: "Hormones & Specialized",
    price: 42000,
    sampleType: "Serum",
    turnaround: "Same Day (6 Hours)",
    fasting: "No fasting required",
    badge: "Wellness",
    icon: "sun",
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=600&q=80",
    description: "Measures circulating vitamin D reserves crucial for bone density, calcium absorption, immune vigor, and fatigue prevention.",
    parameters: ["25-OH Total Vitamin D (Deficient / Insufficient / Optimal / Toxic)"]
  },
  {
    id: "blood-group-rhesus",
    name: "Blood Group Typing & Rhesus (Rh Factor)",
    category: "routine",
    categoryLabel: "Routine Health",
    price: 10000,
    sampleType: "EDTA Whole Blood",
    turnaround: "20 Mins",
    fasting: "No fasting required",
    badge: "Instant ID",
    icon: "tag",
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=600&q=80",
    description: "Accurate determination of ABO blood grouping and Rh(D) status with official medical laboratory card certification.",
    parameters: ["ABO blood group (A, B, AB, or O)", "Rhesus status (Positive or Negative)"]
  },
  {
    id: "uric-acid-test",
    name: "Serum Uric Acid (Gout & Joint Panel)",
    category: "metabolic",
    categoryLabel: "Metabolic & Diabetes",
    price: 14000,
    sampleType: "Serum",
    turnaround: "1 - 2 Hours",
    fasting: "4 hours fasting preferred",
    badge: "Joint Health",
    icon: "alert-circle",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=600&q=80",
    description: "Detects elevated uric acid crystals in the bloodstream associated with painful gout flares and kidney stone propensity.",
    parameters: ["Serum Uric Acid level (mg/dL)"]
  }
];

const PACKAGES = [
  {
    id: "basic-wellness",
    title: "Basic Health Screen",
    subtitle: "Ideal for routine annual checkups & general wellness",
    price: 49000,
    originalPrice: 65000,
    tag: "Most Popular",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=600&q=80",
    testsIncluded: ["Malaria Parasite Smear", "Fasting Blood Sugar", "Complete Blood Count (CBC)", "Urinalysis Routine"],
    turnaround: "Same Day (2 Hours)"
  },
  {
    id: "cardio-diabetic",
    title: "Cardio-Metabolic Panel",
    subtitle: "Tailored for blood sugar & heart cardiovascular health",
    price: 79000,
    originalPrice: 105000,
    tag: "Best Value",
    image: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=600&q=80",
    testsIncluded: ["HbA1c 3-Month Glucose", "Complete Lipid Profile", "Kidney Function (RFT)", "Fasting Blood Sugar"],
    turnaround: "Same Day (3 Hours)"
  },
  {
    id: "executive-full-body",
    title: "Executive Comprehensive Lab",
    subtitle: "Thorough 360° health evaluation of all vital organ systems",
    price: 129000,
    originalPrice: 175000,
    tag: "Complete 360°",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80",
    testsIncluded: ["Full Blood Count (CBC)", "Complete Lipid Panel", "Liver Function (LFT)", "Kidney Function (RFT)", "Thyroid TSH", "Urinalysis"],
    turnaround: "Same Day (4 Hours)"
  }
];
